"""Map Smartraveller destination names to ISO 3166-1 alpha-3 codes.

Smartraveller uses some non-standard names ("South Korea (Republic of Korea)",
"Türkiye", "The Gambia", ...). Every destination on the index page as of
2026-07 has an explicit entry below; a normalising fallback catches minor
future renames. Unmatched names must be logged by the caller, never dropped.
"""

import unicodedata

# Explicit name -> ISO3. Keys are normalised (see _norm) before lookup.
NAME_TO_ISO3 = {
    "afghanistan": "AFG",
    "albania": "ALB",
    "algeria": "DZA",
    "angola": "AGO",
    "argentina": "ARG",
    "armenia": "ARM",
    "austria": "AUT",
    "azerbaijan": "AZE",
    "bahamas": "BHS",
    "bahrain": "BHR",
    "bangladesh": "BGD",
    "belarus": "BLR",
    "belgium": "BEL",
    "belize": "BLZ",
    "benin": "BEN",
    "bhutan": "BTN",
    "bolivia": "BOL",
    "bosnia and herzegovina": "BIH",
    "botswana": "BWA",
    "brazil": "BRA",
    "brunei": "BRN",
    "brunei darussalam": "BRN",
    "bulgaria": "BGR",
    "burkina faso": "BFA",
    "burundi": "BDI",
    "cambodia": "KHM",
    "cameroon": "CMR",
    "canada": "CAN",
    "cape verde": "CPV",
    "cabo verde": "CPV",
    "central african republic": "CAF",
    "chad": "TCD",
    "chile": "CHL",
    "china": "CHN",
    "colombia": "COL",
    "comoros": "COM",
    "cook islands": "COK",
    "costa rica": "CRI",
    "cote d'ivoire": "CIV",
    "cote divoire": "CIV",
    "ivory coast": "CIV",
    "croatia": "HRV",
    "cuba": "CUB",
    "cyprus": "CYP",
    "czech republic": "CZE",
    "czechia": "CZE",
    "democratic republic of the congo": "COD",
    "democratic republic of congo": "COD",
    "republic of the congo": "COG",
    "republic of congo": "COG",
    "congo": "COG",
    "denmark": "DNK",
    "djibouti": "DJI",
    "dominica": "DMA",
    "dominican republic": "DOM",
    "ecuador": "ECU",
    "egypt": "EGY",
    "el salvador": "SLV",
    "equatorial guinea": "GNQ",
    "eritrea": "ERI",
    "estonia": "EST",
    "eswatini": "SWZ",
    "swaziland": "SWZ",
    "ethiopia": "ETH",
    "federated states of micronesia": "FSM",
    "micronesia": "FSM",
    "fiji": "FJI",
    "finland": "FIN",
    "france": "FRA",
    "french polynesia": "PYF",
    "gabon": "GAB",
    "gambia": "GMB",
    "georgia": "GEO",
    "germany": "DEU",
    "ghana": "GHA",
    "greece": "GRC",
    "grenada": "GRD",
    "guam": "GUM",
    "guatemala": "GTM",
    "guinea": "GIN",
    "guinea-bissau": "GNB",
    "guyana": "GUY",
    "haiti": "HTI",
    "honduras": "HND",
    "hong kong": "HKG",
    "hungary": "HUN",
    "iceland": "ISL",
    "india": "IND",
    "indonesia": "IDN",
    "iran": "IRN",
    "iraq": "IRQ",
    "ireland": "IRL",
    "israel": "ISR",
    "israel and the palestinian territories": "ISR",
    "italy": "ITA",
    "jamaica": "JAM",
    "japan": "JPN",
    "jordan": "JOR",
    "kazakhstan": "KAZ",
    "kenya": "KEN",
    "kiribati": "KIR",
    "kosovo": "XKX",
    "kuwait": "KWT",
    "kyrgyz republic": "KGZ",
    "kyrgyzstan": "KGZ",
    "laos": "LAO",
    "latvia": "LVA",
    "lebanon": "LBN",
    "lesotho": "LSO",
    "liberia": "LBR",
    "libya": "LBY",
    "liechtenstein": "LIE",
    "lithuania": "LTU",
    "luxembourg": "LUX",
    "macau": "MAC",
    "macao": "MAC",
    "madagascar": "MDG",
    "malawi": "MWI",
    "malaysia": "MYS",
    "maldives": "MDV",
    "mali": "MLI",
    "malta": "MLT",
    "marshall islands": "MHL",
    "mauritania": "MRT",
    "mauritius": "MUS",
    "mexico": "MEX",
    "moldova": "MDA",
    "monaco": "MCO",
    "mongolia": "MNG",
    "montenegro": "MNE",
    "morocco": "MAR",
    "mozambique": "MOZ",
    "myanmar": "MMR",
    "burma": "MMR",
    "namibia": "NAM",
    "nauru": "NRU",
    "nepal": "NPL",
    "netherlands": "NLD",
    "new caledonia": "NCL",
    "new zealand": "NZL",
    "nicaragua": "NIC",
    "niger": "NER",
    "nigeria": "NGA",
    "niue": "NIU",
    "north korea": "PRK",
    "north macedonia": "MKD",
    "norway": "NOR",
    "oman": "OMN",
    "pakistan": "PAK",
    "palau": "PLW",
    "palestine": "PSE",
    "palestinian territories": "PSE",
    "panama": "PAN",
    "papua new guinea": "PNG",
    "paraguay": "PRY",
    "peru": "PER",
    "philippines": "PHL",
    "poland": "POL",
    "portugal": "PRT",
    "qatar": "QAT",
    "romania": "ROU",
    "russia": "RUS",
    "rwanda": "RWA",
    "saint kitts and nevis": "KNA",
    "saint lucia": "LCA",
    "saint vincent and the grenadines": "VCT",
    "samoa": "WSM",
    "san marino": "SMR",
    "sao tome and principe": "STP",
    "saudi arabia": "SAU",
    "senegal": "SEN",
    "serbia": "SRB",
    "seychelles": "SYC",
    "sierra leone": "SLE",
    "singapore": "SGP",
    "slovakia": "SVK",
    "slovenia": "SVN",
    "solomon islands": "SLB",
    "somalia": "SOM",
    "south africa": "ZAF",
    "south korea": "KOR",
    "south sudan": "SSD",
    "spain": "ESP",
    "sri lanka": "LKA",
    "sudan": "SDN",
    "suriname": "SUR",
    "sweden": "SWE",
    "switzerland": "CHE",
    "syria": "SYR",
    "taiwan": "TWN",
    "tajikistan": "TJK",
    "tanzania": "TZA",
    "thailand": "THA",
    "timor-leste": "TLS",
    "east timor": "TLS",
    "togo": "TGO",
    "tonga": "TON",
    "trinidad and tobago": "TTO",
    "tunisia": "TUN",
    "turkiye": "TUR",
    "turkey": "TUR",
    "turkmenistan": "TKM",
    "tuvalu": "TUV",
    "uganda": "UGA",
    "ukraine": "UKR",
    "united arab emirates": "ARE",
    "united kingdom": "GBR",
    "united states of america": "USA",
    "united states": "USA",
    "uruguay": "URY",
    "uzbekistan": "UZB",
    "vanuatu": "VUT",
    "vatican city": "VAT",
    "holy see": "VAT",
    "venezuela": "VEN",
    "vietnam": "VNM",
    "yemen": "YEM",
    "zambia": "ZMB",
    "zimbabwe": "ZWE",
}


def _norm(name: str) -> str:
    """Normalise a destination name for lookup: strip accents, parentheticals,
    a leading "The ", and collapse whitespace/case."""
    s = unicodedata.normalize("NFKD", name)
    s = "".join(c for c in s if not unicodedata.combining(c))
    s = s.replace("’", "'").strip()
    # Drop any parenthetical qualifiers: "South Korea (Republic of Korea)"
    while "(" in s:
        i, j = s.find("("), s.find(")")
        if j == -1:
            s = s[:i]
            break
        s = s[:i] + s[j + 1:]
    s = " ".join(s.split())
    if s.lower().startswith("the "):
        s = s[4:]
    return s.lower().strip()


def to_iso3(name: str):
    """Return the ISO3 code for a Smartraveller destination name, or None."""
    n = _norm(name)
    if n in NAME_TO_ISO3:
        return NAME_TO_ISO3[n]
    # Fallback: try again without a trailing parenthetical remnant or hyphens
    n2 = n.replace("-", " ")
    return NAME_TO_ISO3.get(n2)
